export const BUILDINGS_REQUEST = 'BUILDINGS_REQUEST';
export const BUILDINGS_SUCCESS = 'BUILDINGS_SUCCESS';
export const BUILDINGS_FAIL = 'BUILDINGS_FAIL';
export const SELECT_BUILDING = 'SELECT_BUILDING';
